# This workflow is triggered by the LOB repo.
name: Azure Pattern Deployment

on: 
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      pattern_name:
        description: "Name of the Azure pattern to deploy."
        required: true
        type: string
      pattern_size:
        description: "Size of the Azure pattern to deploy."
        required: true
        type: string
    # secrets:
    #   token:
    #     description: "Token for accessing the Azure resources."
    #     required: true

run-name: "Azure Pattern Deployment - Run: ${{ github.run_id }}"

jobs:
  Pattern-First-Stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: lob
      - uses: actions/checkout@v4    
        with:
          repository: riwasa/demo-eaas-pattern
          ref: main     
          token: ${{ secrets.DEMO_EAAS_PATTERN_TOKEN }}
          #token: ${{ secrets.token }}
          path: pattern
      - name: First step
        run: echo "This is the first stage of the Azure pattern deployment workflow."
      - name: Show parameters
        run: |
          echo "Pattern Name: ${{ inputs.pattern_name }}"
          echo "Pattern Size: ${{ inputs.pattern_size }}"
      - name: Generate id
        id: generate_id
        shell: pwsh
        run: |
          $id = .\pattern\GenerateId.ps1 -patternName "${{ inputs.pattern_name }}" -patternSize "${{ inputs.pattern_size }}"
          echo "id=$id" >> $env:GITHUB_OUTPUT
      - name: Use generated id
        run: echo "The generated id is ${{ steps.generate_id.outputs.id }}"
      - name: Log in to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep template
        id: deploy
        uses: azure/bicep-deploy@v2
        with:
          name: deploy-pattern-${{ steps.generate_id.outputs.id }}
          type: deployment
          operation: create
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template-file: ./pattern/app-pattern.bicep
          parameters: '{"patternName": "${{ inputs.pattern_name }}", "patternSize": "${{ inputs.pattern_size }}"}'
      - name: Print Deployment Outputs
        run: |
          echo "Pattern Name Output: ${{ steps.deploy.outputs.patternNameOutput }}"
          echo "Pattern Size Output: ${{ steps.deploy.outputs.patternSizeOutput }}"