# This workflow is triggered by the LOB repo.
name: EaaS Pattern Deployment

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      parameters_file:
        description: "Path to the parameters file for the Azure pattern."
        required: true
        type: string

run-name: "EaaS Pattern Deployment - Run: ${{ github.run_id }}"

jobs:
  Deploy-Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Environment
        run: echo "This job sets up the environment for Azure pattern deployment."
      # Checkout LOB repository
      - uses: actions/checkout@v4
        with:
          ref: main
          path: lob
      # Checkout the pattern repository
      - uses: actions/checkout@v4    
        with:
          repository: riwasa/demo-eaas-pattern
          ref: main     
          token: ${{ secrets.DEMO_EAAS_PATTERN_TOKEN }}
          path: pattern
      - name: Log in to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep template
        id: deploy
        uses: azure/bicep-deploy@v2
        with:
          name: deploy-pattern-${{ github.run_id }}
          type: deployment
          operation: create
          location: eastus2
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./pattern/main.bicep
          parameters-file: ./lob/${{ inputs.parameters_file }}
          parameters: '{ "pipelineName": "${{ github.workflow }}", "pipelineRunId": "${{ github.run_id }}", "pipelineTriggerUser": "${{ github.actor }}", "userInputParamFile": "${{ inputs.parameters_file }}" }'
      - name: Calculate lifetime cost
        id: calculate-cost
        shell: pwsh
        run: |
          $lifetimeCost = .\pattern\Calculate-LifetimeCost.ps1 -dailyRunCost "${{ steps.deploy.outputs.dailyRunCost }}" -eaasEndDate "${{ steps.deploy.outputs.eaasEndDate }}"
          echo "lifetimeCost=$lifetimeCost" >> $env:GITHUB_OUTPUT
      - name: Add tags to resource group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group update --name ${{ steps.deploy.outputs.resourceGroupName }} --set tags.lifetimeCost="${{ steps.calculate-cost.outputs.lifetimeCost }}"
