# This workflow is triggered by the LOB repo.
name: Azure Pattern Deployment

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      pattern_name:
        description: "Name of the Azure pattern to deploy."
        required: true
        type: string
      pattern_size:
        description: "Size of the Azure pattern to deploy."
        required: true
        type: string
      parameters_file:
        description: "Path to the parameters file for the Azure pattern."
        required: true
        type: string
    # secrets:
    #   token:
    #     description: "Token for accessing the Azure resources."
    #     required: true

run-name: "Azure Pattern Deployment - Run: ${{ github.run_id }}"

jobs:
  Deploy-Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Environment
        run: echo "This job sets up the environment for Azure pattern deployment."
      - uses: actions/checkout@v4
        with:
          ref: main
          path: pattern
      - name: Log in to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PATTERN }}
      - name: Deploy Bicep template
        id: deploy
        uses: azure/bicep-deploy@v2
        with:
          name: deploy-pattern-${{ github.run_id }}
          type: deployment
          operation: create
          location: "eastus2"
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PATTERN }}
          template-file: ./pattern/main.bicep
          #parameters-file: ./lob/${{ inputs.parameters_file }}
          parameters: '{ "appCatId": "MRNG-20982", "azureRegion": "eastus2", "azureSubscription": "${{ secrets.AZURE_SUBSCRIPTION_ID_PATTERN }}", "eaasEndDate": "2025-12-31", "eaasRequestorTeam": "Team 1", "eaasServiceNowTicketId": "INC1234567", "eaasStampSize": "Small" }'
