# This workflow is triggered by the LOB repo.
name: EaaS Pattern Deployment v2

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      parameters_file:
        description: "Path to the parameters file for the Azure pattern."
        required: true
        type: string

run-name: "EaaS Pattern Deployment v2 - Run: ${{ github.run_id }}"

jobs:
  Calculate-Run-Costs:
    runs-on: ubuntu-latest
    
    outputs:
      lifetimeCost: ${{ steps.calculate-cost.outputs.lifetimeCost }}

    steps:
      - name: Calculate Run Costs
        run: echo "This job calculates the run costs for the EaaS pattern deployment."

      - name: Checkout LOB repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: lob

      - name: Checkout EaaS Pattern repository
        uses: actions/checkout@v4    
        with:
          repository: riwasa/demo-eaas-pattern
          ref: main     
          token: ${{ secrets.DEMO_EAAS_PATTERN_TOKEN }}
          path: pattern

      - name: Calculate lifetime cost
        id: calculate-cost
        shell: pwsh
        run: |
          $lifetimeCost = .\pattern\Calculate-LifetimeCost.ps1 -lobFilePath "./lob/${{ inputs.parameters_file }}" -eaasStampFileRoot "./pattern"
          echo "lifetimeCost=$lifetimeCost" >> $env:GITHUB_OUTPUT

  Deploy-Environment:
    runs-on: ubuntu-latest
    needs: Calculate-Run-Costs
    environment: EaaS
  
    steps:
      - name: Deploy Environment
        run: echo "This job sets up the environment for Azure pattern deployment."
  
      - name: Checkout LOB repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: lob
  
      - name : Checkout EaaS Pattern repository
        uses: actions/checkout@v4    
        with:
          repository: riwasa/demo-eaas-pattern
          ref: main     
          token: ${{ secrets.DEMO_EAAS_PATTERN_TOKEN }}
          path: pattern
  
      - name: Get Azure region
        id: get-region
        shell: pwsh
        run: |
          $azureRegion = .\pattern\Get-AzureRegion.ps1 -filePath "./lob/${{ inputs.parameters_file }}"
          echo "azureRegion=$azureRegion" >> $env:GITHUB_OUTPUT
  
      - name: Log in to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Deploy Bicep template
        id: deploy
        uses: azure/bicep-deploy@v2
        with:
          name: deploy-pattern-${{ github.run_id }}
          type: deployment
          operation: create
          location: ${{ steps.get-region.outputs.azureRegion }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./pattern/main.bicep
          parameters-file: ./lob/${{ inputs.parameters_file }}
          parameters: '{ "adminPassword": "${{ secrets.DEMO_EAAS_ADMIN_PASSWORD }}", "adminUsername": "${{ secrets.DEMO_EAAS_ADMIN_USERNAME }}", "autoShutdownEmailRecipient": "${{ secrets.DEMO_EAAS_AUTO_SHUTDOWN_EMAIL_RECIPIENT }}", "lifetimeCost": "${{ needs.Calculate-Run-Costs.outputs.lifetimeCost }}", "pipelineName": "${{ github.workflow }}", "pipelineRunId": "${{ github.run_id }}", "pipelineTriggerUser": "${{ github.actor }}", "userInputParamFile": "${{ inputs.parameters_file }}" }'

      - name: Output deployment details
        id: output-deployment
        run: |
          echo "Resource Group Name: ${{ steps.deploy.outputs.resourceGroupName }}"
          echo "VM Names: ${{ steps.deploy.outputs.vmNames }}"